name: FeatherMarket
version: ${project.version}
main: com.wasted_ticks.feathermarket.FeatherMarket
api-version: 1.13
depend: [Vault, SmartInvs]
authors: [Wasted_Ticks]
commands:
  market:
    description: market command
    usage: /market
